import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { counterexampleHash, executableInvariantPlanSchema, invariantPlanHash, invariantReplayPlanSchema, type ExecutableInvariantPlan } from "@contracthunter/core";
import { InvariantReplayGenerator } from "./invariant-replay-generator";
import { parseInvariantReplayForgeJson, parseTrustedInvariantReplayForgeResult } from "./invariant-replay-result";
import { validateInvariantReplayWorkspaceIntegrity } from "./invariant-replay-workspace-integrity";
import { InvariantReplayWorkerClient } from "./verification-worker-client";
import { invariantReplayWorkerRequestSchema, REPLAY_MAX_OUTPUT_BYTES, REPLAY_TIMEOUT_MS, workerRequestSchema } from "./verification-worker-protocol";
import { VerificationWorkspaceBuilder } from "./verification-workspace-builder";

const scanId = "11111111-1111-4111-8111-111111111111", hypothesisId = "22222222-2222-4222-8222-222222222222", proposalId = "33333333-3333-4333-8333-333333333333", invariantRunId = "44444444-4444-4444-8444-444444444444", workspaceId = "55555555-5555-4555-8555-555555555555", commit = "a".repeat(40);
const root = path.resolve("packages/scanners/fixtures/invariants");
const common = { schemaVersion: "contracthunter-invariant-plan-v1", scanId, hypothesisId, resolvedCommit: commit, compilerVersion: "0.8.36", actors: ["deployer", "attacker"] };
function fuzz(contract = "VulnerableAccounting"): ExecutableInvariantPlan { return executableInvariantPlanSchema.parse({ ...common, mode: "fuzz-property", primaryContract: contract, primarySourcePath: `contracts/${contract}.sol`, sourceFiles: [`contracts/${contract}.sol`], setup: [{ kind: "deploy", contractName: contract, instanceName: "target" }], fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }], args: [{ kind: "parameter", name: "amount" }] }, property: { name: "accounting", observations: [{ kind: "read-uint", instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }, { kind: "read-balance", target: { kind: "instance", name: "target" }, resultName: "nativeBalance" }], assertions: [{ id: "equal", kind: "uint-eq", actual: "recorded", expected: { kind: "result", name: "nativeBalance" } }] } }); }
function stateful(): ExecutableInvariantPlan { return executableInvariantPlanSchema.parse({ ...common, mode: "stateful-invariant", primaryContract: "StatefulAccessControl", primarySourcePath: "contracts/StatefulAccessControl.sol", sourceFiles: ["contracts/StatefulAccessControl.sol"], setup: [{ kind: "deploy", contractName: "StatefulAccessControl", instanceName: "target" }], handlerActions: [{ name: "touch", instanceName: "target", functionName: "touch", caller: "attacker", parameters: [{ name: "flag", type: "bool" }], args: [{ kind: "parameter", name: "flag" }] }, { name: "takeOwnership", instanceName: "target", functionName: "transferOwnership", caller: "attacker", parameters: [], args: [{ kind: "address", source: "actor", name: "attacker" }] }], properties: [{ name: "ownerStable", observations: [{ kind: "read-address", instanceName: "target", functionName: "owner", resultName: "observedOwner" }], assertions: [{ id: "owner", kind: "address-eq", actual: "observedOwner", expected: { kind: "address", source: "actor", name: "deployer" } }] }] }); }
function replay(plan: ExecutableInvariantPlan, counterexample: unknown, propertyName: string) { return invariantReplayPlanSchema.parse({ schemaVersion: "contracthunter-invariant-replay-v1", scanId, hypothesisId, resolvedCommit: commit, compilerVersion: "0.8.36", proposalId, invariantRunId, invariantPlanHash: invariantPlanHash(plan), propertyName, hypothesisExpectation: "hypothesis-predicts-property-violation", counterexample, counterexampleHash: counterexampleHash(counterexample) }); }
const single = { kind: "single", parserVersion: "foundry-1.7.1-json-v1", parameterValues: [{ name: "amount", type: "uint256", value: "436" }], summary: "Final fuzz case." };
const sequence = { kind: "sequence", parserVersion: "foundry-1.7.1-json-v1", actions: [{ actionName: "touch", parameterValues: [{ name: "flag", type: "bool", value: true }] }, { actionName: "takeOwnership", parameterValues: [] }], summary: "Final handler sequence." };

describe("deterministic invariant replay", () => {
  it("generates a fixed fuzz replay that passes only on the expected violation", async () => { const plan = fuzz(), source = await readFile(path.join(root, plan.primarySourcePath), "utf8"), generated = new InvariantReplayGenerator().generate(replay(plan, single, "accounting"), plan, new Map([[plan.primarySourcePath, source]])); expect(generated.source).toContain("function testReplay_accounting() public"); expect(generated.source).toContain("target.record(436);"); expect(generated.source).toContain('require(!((recorded == nativeBalance)), "CH_REPLAY_NOT_REPRODUCED")'); expect(generated.source).not.toContain("testFuzz"); expect(generated).toEqual(new InvariantReplayGenerator().generate(replay(plan, single, "accounting"), plan, new Map([[plan.primarySourcePath, source]]))); });
  it("renders the exact ordered stateful sequence with typed bool values", async () => { const plan = stateful(), source = await readFile(path.join(root, plan.primarySourcePath), "utf8"), generated = new InvariantReplayGenerator().generate(replay(plan, sequence, "ownerStable"), plan, new Map([[plan.primarySourcePath, source]])); expect(generated.source.indexOf("target.touch(true)")).toBeLessThan(generated.source.indexOf("target.transferOwnership(actor_attacker)")); expect(generated.source.match(/vm\.prank\(actor_attacker\)/g)).toHaveLength(2); });
  it("interprets only the exact generated replay result", () => { const value = replay(fuzz(), single, "accounting"), json = (status: string, reason: string | null) => JSON.stringify({ "test/ContractHunterReplay.t.sol:ContractHunterReplayTest": { test_results: { "testReplay_accounting()": { status, reason } } } }); expect(parseInvariantReplayForgeJson(json("Success", null), value)).toBe("reproduced"); expect(parseInvariantReplayForgeJson(json("Failure", "CH_REPLAY_NOT_REPRODUCED"), value)).toBe("not-reproduced"); expect(parseInvariantReplayForgeJson(json("Failure", "other"), value)).toBeNull(); });
  it("rejects malformed, additional, truncated, counterexample-bearing, and exit-inconsistent replay output", () => {
    const value = replay(fuzz(), single, "accounting"), suite = "test/ContractHunterReplay.t.sol:ContractHunterReplayTest";
    const json = (tests: Record<string, unknown>) => JSON.stringify({ [suite]: { test_results: tests } }), success = { status: "Success", reason: null };
    for (const malformed of ["{", json({}), json({ "testReplay_accounting()": success, "testUnexpected()": success }), json({ "testReplay_accounting()": { ...success, counterexample: { Single: {} } } }), json({ "testReplay_accounting()": { status: "Success", reason: "ambiguous" } }), json({ "testReplay_accounting()": { status: "Failure", reason: "prefix CH_REPLAY_NOT_REPRODUCED suffix" } })]) expect(parseInvariantReplayForgeJson(malformed, value)).toBeNull();
    const reproduced = json({ "testReplay_accounting()": success }), notReproduced = json({ "testReplay_accounting()": { status: "Failure", reason: "CH_REPLAY_NOT_REPRODUCED" } });
    expect(parseTrustedInvariantReplayForgeResult(reproduced, value, 1, false)).toBeNull(); expect(parseTrustedInvariantReplayForgeResult(notReproduced, value, 0, false)).toBeNull(); expect(parseTrustedInvariantReplayForgeResult(reproduced, value, 0, true)).toBeNull();
  });
  it("accepts only the fixed replay worker request surface", () => { const request = { command: "execute-invariant-replay", replayRunId: invariantRunId, workspaceId, scanId, hypothesisId, resolvedCommit: commit, compilerVersion: "0.8.36", invariantPlanHash: "a".repeat(64), replayPlanHash: "b".repeat(64), counterexampleHash: "c".repeat(64), timeoutMs: REPLAY_TIMEOUT_MS, maxOutputBytes: REPLAY_MAX_OUTPUT_BYTES }; expect(invariantReplayWorkerRequestSchema.safeParse(request).success).toBe(true); expect(workerRequestSchema.safeParse(request).success).toBe(true); for (const field of [{ args: ["--ffi"] }, { executable: "sh" }, { env: { RPC_URL: "x" } }, { timeoutMs: 0 }, { workspaceId: "../x" }]) expect(invariantReplayWorkerRequestSchema.safeParse({ ...request, ...field }).success).toBe(false); });
  it("constructs a strict replay request without leaking the local workspacePath field", async () => {
    const base = await mkdtemp(path.join(tmpdir(), "ch-replay-client-"));
    try { const workspace = path.join(base, workspaceId); await mkdir(workspace); const result = await new InvariantReplayWorkerClient(base, path.join(base, "missing.sock")).run({ replayRunId: invariantRunId, workspacePath: workspace, scanId, hypothesisId, resolvedCommit: commit, compilerVersion: "0.8.36", invariantPlanHash: "a".repeat(64), replayPlanHash: "b".repeat(64), counterexampleHash: "c".repeat(64) }); expect(result).toMatchObject({ status: "refused", errorCode: "replay_worker_unavailable" }); }
    finally { await rm(base, { recursive: true, force: true }); }
  });
});

describe("replay workspace integrity", () => {
  const paths: string[] = []; afterEach(async () => { await Promise.all(paths.splice(0).map((item) => rm(item, { recursive: true, force: true }))); });
  it("revalidates byte-identical generated content and rejects a changed harness", async () => { const base = await mkdtemp(path.join(tmpdir(), "ch-replay-")); paths.push(base); const repositories = path.join(base, "repos"), workspaces = path.join(base, "workspaces"), repository = path.join(repositories, scanId); await mkdir(path.join(repository, "contracts"), { recursive: true }); await writeFile(path.join(repository, "contracts/VulnerableAccounting.sol"), await readFile(path.join(root, "contracts/VulnerableAccounting.sol"))); const plan = fuzz(), built = await new VerificationWorkspaceBuilder({ verificationRoot: workspaces, repositoryRoot: repositories, acceptedCompilerVersions: ["0.8.36"], approvedSourceRoots: ["contracts"], generatorVersion: "0.2.0" }).buildInvariantReplay({ workspaceId, repositoryPath: repository, replayPlan: replay(plan, single, "accounting"), invariantPlan: plan }); expect(await validateInvariantReplayWorkspaceIntegrity(built.workspacePath)).toEqual(built.manifest); await writeFile(path.join(built.workspacePath, built.manifest.generatedHarnessPath), "contract Changed {}"); await expect(validateInvariantReplayWorkspaceIntegrity(built.workspacePath)).rejects.toThrow(); });
});
