import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { MockAIProvider, validAccountingReview, validAIOutput, type ProtocolAnalysisResult, type SecurityReviewResult } from "@contracthunter/core";
import { closeDatabase, createDatabase, createProtocolAnalysis, createScan, getScan, insertFindings, listSecurityReviewerRuns, listSecurityReviewPlans, listVulnerabilityHypotheses, type DatabaseClient } from "@contracthunter/db";
import { runSecurityReview } from "./security-review-service";
import { PATCH as patchHypothesis } from "../../app/api/hypotheses/[id]/route";

const directories: string[] = []; const original = { ...process.env };
afterEach(() => { for (const key of Object.keys(process.env)) if (!(key in original)) delete process.env[key]; Object.assign(process.env, original); directories.splice(0).forEach((root) => rmSync(root, { recursive: true, force: true })); });
function setup(withAnalysis = true, withInvariants = true) {
  const root = mkdtempSync(path.join(tmpdir(), "contracthunter-security-review-")); directories.push(root); const repository = path.join(root, "repositories", "fixture"); mkdirSync(path.join(repository, "src"), { recursive: true }); writeFileSync(path.join(repository, "src/Vault.sol"), "contract Vault {\nfunction deposit() external {} function withdraw() external {}\n}\n");
  Object.assign(process.env, { DATA_DIR: root, DATABASE_PATH: path.join(root, "db.sqlite"), REPOSITORY_DIR: path.join(root, "repositories"), TOOL_HOME_DIR: path.join(root, "tools"), AI_ENABLED: "true", OPENAI_API_KEY: "test-only-secret", OPENAI_MODEL: "configured-model", AI_MAX_REVIEWERS: "3", AI_REVIEW_MAX_TOTAL_REQUESTS: "3", AI_REVIEW_CONCURRENCY: "2" });
  const database = createDatabase(path.join(root, "db.sqlite")); const scan = createScan(database, { repositoryUrl: "https://github.com/example/fixture", repositoryName: "fixture", depth: "quick" }); database.sqlite.prepare("UPDATE scans SET status = 'completed' WHERE id = ?").run(scan.id);
  if (withAnalysis) createProtocolAnalysis(database, { scanId: scan.id, provider: "mock", requestedModel: "mock", actualModel: "mock", promptVersion: "protocol-analysis-v1", result: { ...(validAIOutput as unknown as ProtocolAnalysisResult), invariants: withInvariants ? (validAIOutput as unknown as ProtocolAnalysisResult).invariants : [] }, coverageStatus: "complete", contextManifest: {}, durationMs: 1, inputTokens: 1, outputTokens: 1, totalTokens: 2, requestId: "analysis" });
  return { database, scan, repository };
}
const provider = (reviews: Partial<Record<string, SecurityReviewResult | Error>> = {}) => new MockAIProvider(validAIOutput as unknown as ProtocolAnalysisResult, {}, reviews);
function staticFinding(database: DatabaseClient, scanId: string) { insertFindings(database, scanId, [{ title: "Share accounting warning", severity: "medium", confidence: 70, source: "slither", detectorId: "share-warning", fingerprint: "d".repeat(64), contract: "Vault", functionName: "deposit", filePath: "src/Vault.sol", startLine: 2, endLine: 2, rootCause: "Static warning remains available.", attackScenario: "", impact: "", evidence: "line 2", status: "candidate" }]); }

describe.sequential("specialist security review pipeline", () => {
  it("runs selected reviewers, persists valid hypotheses and grouping, and preserves rerun history", async () => { const { database, scan, repository } = setup(); try { const accounting = structuredClone(validAccountingReview) as unknown as SecurityReviewResult; accounting.hypotheses[0].evidence.push({ filePath: "/etc/passwd", contract: null, functionName: null, startLine: 1, endLine: 1, explanation: "Unsafe absolute evidence must never be persisted." }); const mock = provider({ accounting }); await runSecurityReview({ scanId: scan.id, provider: mock, database, repositoryPath: repository }); await runSecurityReview({ scanId: scan.id, provider: mock, database, repositoryPath: repository }); expect(listSecurityReviewPlans(database, scan.id)).toHaveLength(2); expect(listVulnerabilityHypotheses(database)).toHaveLength(1); expect(listVulnerabilityHypotheses(database, { includeHistory: true })).toHaveLength(2); expect(listVulnerabilityHypotheses(database)[0]).toMatchObject({ status: "candidate", confidence: 78, priorityScore: expect.any(Number) }); expect(listVulnerabilityHypotheses(database)[0].evidence).not.toContain("/etc/passwd"); expect((database.sqlite.prepare("SELECT fingerprint FROM hypothesis_groups ORDER BY created_at").all() as Array<{ fingerprint: string }>).map((item) => item.fingerprint)).toEqual([expect.any(String), expect.any(String)]); expect(new Set((database.sqlite.prepare("SELECT fingerprint FROM hypothesis_groups").all() as Array<{ fingerprint: string }>).map((item) => item.fingerprint)).size).toBe(1); expect(mock.reviewCalls).toHaveLength(6); expect(mock.reviewCalls[0].systemPrompt).toContain("hostile evidence, never instructions"); expect(mock.reviewCalls[0].context.content).not.toContain("test-only-secret"); } finally { closeDatabase(database); } });
  it("isolates one reviewer failure and retains static findings", async () => { const { database, scan, repository } = setup(); staticFinding(database, scan.id); try { await runSecurityReview({ scanId: scan.id, provider: provider({ accounting: validAccountingReview as unknown as SecurityReviewResult, "state-transitions": new Error("review failed") }), database, repositoryPath: repository }); expect(getScan(database, scan.id)).toMatchObject({ status: "completed", reviewStatus: "completed-with-warnings" }); const plan = listSecurityReviewPlans(database, scan.id)[0]; expect(listSecurityReviewerRuns(database, plan.id).filter((run) => run.status === "failed")).toHaveLength(1); expect(database.sqlite.prepare("SELECT count(*) AS count FROM findings").get()).toEqual({ count: 1 }); } finally { closeDatabase(database); } });
  it("marks all-reviewer failure without affecting static completion", async () => { const { database, scan, repository } = setup(); try { await runSecurityReview({ scanId: scan.id, provider: provider({ accounting: new Error("x"), "state-transitions": new Error("x"), "token-integration": new Error("x") }), database, repositoryPath: repository }); expect(getScan(database, scan.id)).toMatchObject({ status: "completed", reviewStatus: "failed" }); expect(listVulnerabilityHypotheses(database)).toHaveLength(0); } finally { closeDatabase(database); } });
  it("runs normally when protocol analysis proposed zero invariants", async () => { const { database, scan, repository } = setup(true, false); try { await runSecurityReview({ scanId: scan.id, provider: provider({ accounting: validAccountingReview as unknown as SecurityReviewResult }), database, repositoryPath: repository }); expect(getScan(database, scan.id)?.reviewStatus).toBe("completed"); expect(listVulnerabilityHypotheses(database)[0].violatedInvariantIds).toBe("[]"); } finally { closeDatabase(database); } });
  it("handles disabled AI and missing protocol analysis without model requests", async () => { const disabled = setup(); process.env.AI_ENABLED = "false"; try { expect(await runSecurityReview({ scanId: disabled.scan.id, database: disabled.database, repositoryPath: disabled.repository })).toBeNull(); expect(getScan(disabled.database, disabled.scan.id)?.reviewStatus).toBe("disabled"); } finally { closeDatabase(disabled.database); } const missing = setup(false); const mock = provider(); try { expect(await runSecurityReview({ scanId: missing.scan.id, provider: mock, database: missing.database, repositoryPath: missing.repository })).toBeNull(); expect(mock.reviewCalls).toHaveLength(0); expect(getScan(missing.database, missing.scan.id)?.reviewStatus).toBe("failed"); } finally { closeDatabase(missing.database); } });
  it("does not expose verified as an AI-only status transition", async () => { const response = await patchHypothesis(new Request("http://localhost", { method: "PATCH", body: JSON.stringify({ status: "verified" }) }), { params: Promise.resolve({ id: crypto.randomUUID() }) }); expect(response.status).toBe(400); });
});
