import Link from "next/link";
import { evidenceClasses, hypothesisStatuses, securityReviewerIds, severities, type EvidenceClass, type HypothesisStatus, type Severity } from "@contracthunter/core";
import { getDatabase, listScans, listVulnerabilityHypotheses } from "@contracthunter/db";
import { SeverityBadge } from "@/components/badges";
export const dynamic = "force-dynamic";
type Query = { scan?: string; severity?: string; category?: string; reviewer?: string; status?: string; minimumConfidence?: string; evidenceClass?: string };
export default async function HypothesesPage({ searchParams }: { searchParams: Promise<Query> }) {
  const query = await searchParams; const database = getDatabase(); const scans = listScans(database); const scanId = scans.some((scan) => scan.id === query.scan) ? query.scan : undefined; const severity = severities.includes(query.severity as Severity) ? query.severity as Severity : undefined; const status = hypothesisStatuses.includes(query.status as HypothesisStatus) ? query.status as HypothesisStatus : undefined; const reviewerId = securityReviewerIds.includes(query.reviewer as typeof securityReviewerIds[number]) ? query.reviewer : undefined; const evidenceClass = evidenceClasses.includes(query.evidenceClass as EvidenceClass) ? query.evidenceClass : undefined; const minimumConfidence = query.minimumConfidence && /^\d+$/.test(query.minimumConfidence) ? Math.min(85, Number(query.minimumConfidence)) : undefined;
  const all = listVulnerabilityHypotheses(database, { scanId, severity, category: query.category || undefined, reviewerId, status, minimumConfidence, evidenceClass }); const categories = [...new Set(listVulnerabilityHypotheses(database).map((item) => item.category))].sort();
  return <><header className="page-head"><div><div className="eyebrow">What should I investigate first?</div><h1>Hypotheses</h1><p className="subhead">Evidence-ranked, unverified AI explanations of how protocol guarantees might fail.</p></div></header><div className="mock-note"><strong>Unverified AI hypotheses.</strong> These candidates require safe local dynamic verification before they can become verified vulnerabilities.</div>
    <form className="filter-row hypothesis-filters"><select name="scan" defaultValue={scanId ?? ""}><option value="">All hunts</option>{scans.map((scan) => <option key={scan.id} value={scan.id}>{scan.repositoryName}</option>)}</select><select name="severity" defaultValue={severity ?? ""}><option value="">All severities</option>{severities.map((item) => <option key={item}>{item}</option>)}</select><select name="category" defaultValue={query.category ?? ""}><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select name="reviewer" defaultValue={reviewerId ?? ""}><option value="">All reviewers</option>{securityReviewerIds.map((item) => <option key={item}>{item}</option>)}</select><select name="status" defaultValue={status ?? ""}><option value="">All statuses</option>{hypothesisStatuses.filter((item) => item !== "verified").map((item) => <option key={item}>{item}</option>)}</select><input name="minimumConfidence" type="number" min="0" max="85" placeholder="Min confidence" defaultValue={minimumConfidence} /><select name="evidenceClass" defaultValue={evidenceClass ?? ""}><option value="">All evidence classes</option>{evidenceClasses.map((item) => <option key={item}>{item}</option>)}</select><button className="button">FILTER</button></form>
    <div className="table-wrap"><table><thead><tr><th>Priority</th><th>Severity</th><th>Hypothesis</th><th>Category</th><th>Confidence</th><th>Reviewer</th><th>Evidence</th><th>Invariant</th><th>Status</th></tr></thead><tbody>{all.map((item) => { const invariants = parseList(item.violatedInvariantIds); return <tr key={item.id}><td className="mono"><strong>{item.priorityScore}</strong></td><td><SeverityBadge value={item.severity} /></td><td className="finding-title"><Link className="repo" href={`/hypotheses/${item.id}`}>{item.title}</Link></td><td>{item.category}</td><td>{item.confidence}%</td><td>{item.reviewerId}</td><td>{item.evidenceClasses.join(" + ")}</td><td>{invariants.length ? `${invariants.length} linked` : "—"}</td><td><span className={`badge ${item.status === "rejected" ? "red" : item.status === "likely-valid" ? "amber" : item.status === "investigating" ? "blue" : "gray"}`}>{item.status}</span></td></tr>; })}{!all.length && <tr><td colSpan={9} className="empty">No hypotheses match these filters.</td></tr>}</tbody></table></div></>;
}
const parseList = (value: string): string[] => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } };
