import { describe, expect, it } from "vitest";
import { counterexampleHash, executableInvariantPlanSchema, invariantPlanHash, invariantProposalSchema, invariantReplayPlanHash, invariantReplayPlanSchema, validateReplayAgainstInvariant } from "./index";

const identity = { scanId: "11111111-1111-4111-8111-111111111111", hypothesisId: "22222222-2222-4222-8222-222222222222", resolvedCommit: "a".repeat(40), compilerVersion: "0.8.36" };
const plan = executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", ...identity, mode: "fuzz-property", primaryContract: "VulnerableAccounting", primarySourcePath: "contracts/VulnerableAccounting.sol", sourceFiles: ["contracts/VulnerableAccounting.sol"], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: "VulnerableAccounting", instanceName: "target" }], fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }, { name: "flag", type: "bool" }], args: [{ kind: "parameter", name: "amount" }, { kind: "parameter", name: "flag" }] }, property: { name: "accounting", observations: [{ kind: "read-uint", instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }], assertions: [{ id: "zero", kind: "uint-eq", actual: "recorded", expected: "0" }] } });
const counterexample = { kind: "single" as const, parserVersion: "foundry-1.7.1-json-v1" as const, parameterValues: [{ name: "amount", type: "uint256" as const, value: "436" }, { name: "flag", type: "bool" as const, value: true }], summary: "Bounded final counterexample." };
const replay = () => invariantReplayPlanSchema.parse({ schemaVersion: "contracthunter-invariant-replay-v1", ...identity, proposalId: "33333333-3333-4333-8333-333333333333", invariantRunId: "44444444-4444-4444-8444-444444444444", invariantPlanHash: invariantPlanHash(plan), propertyName: "accounting", hypothesisExpectation: "hypothesis-predicts-property-violation", counterexample, counterexampleHash: counterexampleHash(counterexample) });

describe("canonical invariant counterexamples and replay identity", () => {
  it("serializes and hashes fuzz values deterministically", () => { expect(counterexampleHash(counterexample)).toBe(counterexampleHash(structuredClone(counterexample))); expect(invariantReplayPlanHash(replay())).toBe(invariantReplayPlanHash(replay())); });
  it("changes the hash for a uint or bool modification", () => { expect(counterexampleHash({ ...counterexample, parameterValues: [{ ...counterexample.parameterValues[0], value: "437" }, counterexample.parameterValues[1]] })).not.toBe(counterexampleHash(counterexample)); expect(counterexampleHash({ ...counterexample, parameterValues: [counterexample.parameterValues[0], { ...counterexample.parameterValues[1], value: false }] })).not.toBe(counterexampleHash(counterexample)); });
  it("preserves stateful action order in canonical identity", () => { const first = { kind: "sequence" as const, parserVersion: "foundry-1.7.1-json-v1" as const, actions: [{ actionName: "first", parameterValues: [] }, { actionName: "second", parameterValues: [] }], summary: "Sequence." }; expect(counterexampleHash(first)).not.toBe(counterexampleHash({ ...first, actions: [...first.actions].reverse() })); });
  it("rejects a changed counterexample hash", () => { expect(invariantReplayPlanSchema.safeParse({ ...replay(), counterexampleHash: "0".repeat(64) }).success).toBe(false); });
  it("rejects changed plan identity, compiler, commit, actor binding, or parameter mapping", () => { if (plan.mode !== "fuzz-property") throw new Error("fixture mode"); const value = replay(); validateReplayAgainstInvariant(value, plan); for (const changed of [{ ...plan, resolvedCommit: "b".repeat(40) }, { ...plan, compilerVersion: "0.8.35" }, { ...plan, fuzzAction: { ...plan.fuzzAction, caller: "deployer" } }]) expect(() => validateReplayAgainstInvariant(value, executableInvariantPlanSchema.parse(changed))).toThrow(); expect(() => validateReplayAgainstInvariant(value, executableInvariantPlanSchema.parse({ ...plan, fuzzAction: { ...plan.fuzzAction, parameters: [{ name: "other", type: "uint256" }, plan.fuzzAction.parameters[1]], args: [{ kind: "parameter", name: "other" }, { kind: "parameter", name: "flag" }] } }))).toThrow(); });
  it("permits only the supported hypothesis expectation without granting evidence authority", () => { const semantic = structuredClone(plan) as Record<string, unknown>; for (const field of ["schemaVersion", "scanId", "hypothesisId", "resolvedCommit", "compilerVersion", "primarySourcePath", "sourceFiles"]) delete semantic[field]; const base = { status: "generated", semantics: semantic, hypothesisExpectation: "hypothesis-predicts-property-violation", relationRationale: "The hypothesis predicts this property can be broken.", rationale: "Bounded test.", limitations: [], notPlannableReasons: [] }; expect(invariantProposalSchema.safeParse(base).success).toBe(true); expect(invariantProposalSchema.safeParse({ ...base, hypothesisExpectation: "supports" }).success).toBe(false); });
});
