import { describe, expect, it } from "vitest";
import { SecurityReviewPlanner, correlateHypotheses, passesHypothesisQuality, securityReviewResultSchema, validAccountingReview, type ProtocolAnalysisResult, type QualityHypothesis } from "./index";

function protocol(type: ProtocolAnalysisResult["protocol"]["types"][number]): ProtocolAnalysisResult { return { protocol: { name: type, types: [type], summary: `${type} protocol`, architectureSummary: `${type} architecture`, confidence: 80 }, assets: [], roles: [], entryPoints: [], criticalState: [], externalDependencies: [], flows: [], trustAssumptions: [], invariants: [], limitations: [] }; }
describe("SecurityReviewPlanner", () => {
  const planner = new SecurityReviewPlanner();
  it.each([["vault", "vault"], ["lending", "lending"], ["bridge", "bridge"]] as const)("selects %s specialists deterministically", (type, expected) => { const context = { protocol: protocol(type), invariantCount: 0, investigationCategories: [] }; const first = planner.plan(context, 10); expect(first.selected.map((item) => item.reviewerId)).toContain(expected); expect(planner.plan(context, 10)).toEqual(first); });
  it("skips irrelevant reviewers and obeys the hard maximum", () => { const plan = planner.plan({ protocol: protocol("token"), invariantCount: 0, investigationCategories: [] }, 3); expect(plan.selected).toHaveLength(3); expect(plan.skipped.some((item) => item.reviewerId === "bridge" && item.reason.includes("Not relevant"))).toBe(true); });
});

const valid = { reviewer: "accounting", summary: "Reviewed share accounting against concrete code evidence.", hypotheses: [], areasReviewed: [], limitations: [] } as const;
describe("security review structured output", () => {
  it("accepts valid zero-hypothesis output and rejects malformed, unknown, invalid severity, and over-confidence output", () => { expect(securityReviewResultSchema.parse(valid).hypotheses).toEqual([]); expect(securityReviewResultSchema.safeParse({ ...valid, unexpected: true }).success).toBe(false); expect(securityReviewResultSchema.safeParse({ ...valid, hypotheses: [{ severity: "extreme" }] }).success).toBe(false); expect(securityReviewResultSchema.safeParse({ ...valid, hypotheses: [{ title: "x", category: "x", severity: "high", severityJustification: "x", confidence: 86 }] }).success).toBe(false); });
  it("rejects an otherwise complete hypothesis with missing evidence", () => { const candidate = structuredClone(validAccountingReview); delete (candidate.hypotheses[0] as unknown as { evidence?: unknown }).evidence; expect(securityReviewResultSchema.safeParse(candidate).success).toBe(false); });
});

function quality(overrides: Partial<QualityHypothesis> = {}): QualityHypothesis { return { title: "Post-transfer denominator dilutes minted vault shares", category: "accounting", severity: "high", severityJustification: "User ownership can be redistributed.", confidence: 75, summary: "Share minting reads a balance that already includes the incoming user deposit.", rootCause: "The implementation transfers assets before calculating the share conversion denominator.", preconditions: ["Existing non-zero supply"], attackPath: ["Deposit after another user"], impact: "The depositor receives fewer shares than its proportional contribution.", affectedAssets: ["asset"], affectedContracts: ["Vault"], affectedFunctions: ["deposit"], evidence: [{ filePath: "src/Vault.sol", contract: "Vault", functionName: "deposit", startLine: 2, endLine: 2, explanation: "The line contains the affected deposit entry point.", valid: true, validationError: null }], violatedInvariants: [], relatedInvestigations: [], falsePositiveRisks: ["A snapshot may exist elsewhere"], verificationStrategy: ["Write a local boundary unit test"], violatedInvariantIds: [], relatedInvestigationIds: [], ...overrides }; }
describe("hypothesis quality and grouping", () => {
  it("filters vague and missing-evidence hypotheses", () => { expect(passesHypothesisQuality(quality())).toBe(true); expect(passesHypothesisQuality(quality({ summary: "This contract may be vulnerable." }))).toBe(false); expect(passesHypothesisQuality(quality({ evidence: [] }))).toBe(false); });
  it("groups matching locations stably while preserving distinct functions and weakly weights AI overlap", () => { const base = quality(); const map = (id: string, reviewerId: string, fn = "deposit") => ({ id, reviewerId, category: base.category, severity: base.severity, confidence: base.confidence, rootCause: base.rootCause, evidence: [{ ...base.evidence[0], functionName: fn }], violatedInvariantIds: [], relatedInvestigationIds: [] }); const grouped = correlateHypotheses([map("b", "vault"), map("a", "accounting"), map("c", "accounting", "withdraw")]); expect(grouped).toHaveLength(2); expect(grouped.find((item) => item.memberIds.length === 2)?.reasons.join(" ")).toContain("not independent engines"); expect(correlateHypotheses([map("a", "accounting"), map("b", "vault")])).toEqual(correlateHypotheses([map("b", "vault"), map("a", "accounting")])); });
  it("treats static corroboration as stronger than another AI reviewer", () => { const base = quality(); const item = (id: string, reviewerId: string, staticId?: string) => ({ id, reviewerId, category: base.category, severity: base.severity, confidence: base.confidence, rootCause: base.rootCause, evidence: base.evidence, violatedInvariantIds: [], relatedInvestigationIds: staticId ? [staticId] : [] }); const ai = correlateHypotheses([item("a", "accounting"), item("b", "vault")])[0]; const staticLinked = correlateHypotheses([item("a", "accounting", "investigation")])[0]; expect(staticLinked.priorityScore).toBeGreaterThan(ai.priorityScore); });
});
