import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { executableInvariantPlanSchema, invariantPlanHash, type ExecutableInvariantEvidence, type ProtocolAnalysisResult, validAIOutput } from "@contracthunter/core";
import { closeDatabase, completeExecutableInvariantRun, createDatabase, createExecutableInvariantProposal, createExecutableInvariantRun, createProtocolAnalysis, createScan, createSecurityReviewerRun, createSecurityReviewPlan, getVulnerabilityHypothesis, insertVulnerabilityHypotheses, listHypothesisInvariantReplayArtifacts, listHypothesisInvariantReplayRuns, listHypothesisLifecycleTransitions, listInvariantEvidenceReviews, markExecutableInvariantRunRunning, type DatabaseClient } from "@contracthunter/db";
import { VerificationWorkspaceBuilder, type InvariantReplayWorkerResult } from "@contracthunter/scanners";
import { InvariantReplayService } from "./invariant-replay-service";

let directory: string, repositories: string, workspaces: string, database: DatabaseClient, scanId: string, hypothesisId: string;
const commit = "a".repeat(40), fixture = path.resolve("packages/scanners/fixtures/invariants/contracts/VulnerableAccounting.sol");
beforeEach(() => {
  directory = mkdtempSync(path.join(tmpdir(), "ch-replay-service-")); repositories = path.join(directory, "repos"); workspaces = path.join(directory, "workspaces"); database = createDatabase(path.join(directory, "test.db"));
  const scan = createScan(database, { repositoryUrl: "https://example.invalid/synthetic", repositoryName: "synthetic", depth: "quick" }); scanId = scan.id; database.sqlite.prepare("UPDATE scans SET status='completed', resolved_commit=?, compiler_status='ready', compiler_versions=? WHERE id=?").run(commit, JSON.stringify(["0.8.36"]), scanId);
  mkdirSync(path.join(repositories, scanId, "contracts"), { recursive: true }); writeFileSync(path.join(repositories, scanId, "contracts/VulnerableAccounting.sol"), readFileSync(fixture));
  const analysis = createProtocolAnalysis(database, { scanId, provider: "mock", requestedModel: "mock", actualModel: "mock", promptVersion: "protocol-analysis-v1", result: validAIOutput as unknown as ProtocolAnalysisResult, coverageStatus: "complete", contextManifest: {}, durationMs: 1, inputTokens: 1, outputTokens: 1, totalTokens: 2, requestId: "analysis" });
  const review = createSecurityReviewPlan(database, { scanId, protocolAnalysisId: analysis.id, plan: { selected: [], skipped: [], estimatedRequestCount: 0 }, estimatedSourceBytes: 0 }), reviewer = createSecurityReviewerRun(database, { planId: review.id, scanId, protocolAnalysisId: analysis.id, reviewerId: "fixture", reviewerName: "Fixture", selectionReason: "Fixture", promptVersion: "fixture-v1", provider: "mock", requestedModel: "mock", contextManifest: {} });
  hypothesisId = insertVulnerabilityHypotheses(database, [{ scanId, protocolAnalysisId: analysis.id, reviewerId: "fixture", reviewerRunId: reviewer.id, title: "Accounting can diverge", category: "state-transition", severity: "high", severityJustification: "Fixture", confidence: 80, summary: "Accounting can diverge from native balance.", rootCause: "record accepts unfunded amounts", preconditions: "[]", attackPath: "[]", impact: "Incorrect accounting", affectedAssets: "[]", affectedContracts: "[]", affectedFunctions: "[]", evidence: "[]", violatedInvariantIds: "[]", relatedInvestigationIds: "[]", falsePositiveRisks: "[]", verificationStrategy: "[]" }])[0].id;
});
afterEach(() => { closeDatabase(database); rmSync(directory, { recursive: true, force: true }); vi.restoreAllMocks(); });
function plan() { return executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", mode: "fuzz-property", scanId, hypothesisId, resolvedCommit: commit, compilerVersion: "0.8.36", primaryContract: "VulnerableAccounting", primarySourcePath: "contracts/VulnerableAccounting.sol", sourceFiles: ["contracts/VulnerableAccounting.sol"], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: "VulnerableAccounting", instanceName: "target" }], fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }], args: [{ kind: "parameter", name: "amount" }] }, property: { name: "accounting", observations: [{ kind: "read-uint", instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }, { kind: "read-balance", target: { kind: "instance", name: "target" }, resultName: "nativeBalance" }], assertions: [{ id: "equal", kind: "uint-eq", actual: "recorded", expected: { kind: "result", name: "nativeBalance" } }] } }); }
function proposal() { const value = plan(); return createExecutableInvariantProposal(database, { hypothesisId, scanId, result: { status: "generated", plan: value, planHash: invariantPlanHash(value), hypothesisExpectation: "hypothesis-predicts-property-violation", relationRationale: "The hypothesis predicts accounting divergence.", rationale: "Test conservation.", limitations: [], notPlannableReasons: [], failureCode: null, provenance: { provider: "mock", requestedModel: "mock", actualModel: "mock", promptVersion: "invariant-plan-v1", generatedAt: new Date().toISOString(), inputTokens: 1, outputTokens: 1, totalTokens: 2, estimatedCostUsd: 0, durationMs: 1, sourceFileCount: 1, totalSourceBytes: 1, sourceContextTruncated: false } }, contextManifest: {}, requestId: null }); }
function invariantRun(counterexample = true) { const run = createExecutableInvariantRun(database, { plan: plan() }); markExecutableInvariantRunRunning(database, run.id); const evidence: ExecutableInvariantEvidence = { planHash: invariantPlanHash(plan()), mode: "fuzz-property", propertyName: "accounting", configuredRuns: 128, configuredDepth: null, runsExecuted: counterexample ? 0 : 128, propertyOutcome: counterexample ? "counterexample-found" : "held-within-bounds", hypothesisRelation: counterexample ? "unreviewed" : "neutral", compilerVersion: "0.8.36", isolationProvider: "docker-verification-worker-v1", counterexample: counterexample ? { kind: "single", parserVersion: "foundry-1.7.1-json-v1", parameterValues: [{ name: "amount", type: "uint256", value: "436" }], summary: "Final case." } : null, summary: counterexample ? "Counterexample found." : "No counterexample found within configured runs." }; return completeExecutableInvariantRun(database, run.id, { evidence: [evidence], testCount: 1, passedCount: counterexample ? 0 : 1, failedCount: counterexample ? 1 : 0, runsExecuted: evidence.runsExecuted, stdoutSummary: "bounded", stderrSummary: "", contentFingerprint: "b".repeat(64), isolationMetadata: "{}", exitCode: counterexample ? 1 : 0, durationMs: 1 }); }
function worker(outcome: "reproduced" | "not-reproduced"): InvariantReplayWorkerResult { return { status: "completed", outcome, exitCode: outcome === "reproduced" ? 0 : 1, durationMs: 4, timedOut: false, outputTruncated: false, errorCode: null, errorMessage: null, replayPlanHash: "0".repeat(64), counterexampleHash: "0".repeat(64), compilerIdentity: { version: "0.8.36", executablePath: "/trusted" }, isolation: { providerId: "docker-verification-worker-v1", isolationVersion: "1", networkAccess: "disabled", networkIsolated: true, processIsolated: true, workerUid: 10002, resourceLimitsApplied: { maxCpuTimeSeconds: 61, maxVirtualMemoryBytes: 2_147_483_648, maxProcesses: 64, maxOpenFiles: 256, maxFileSizeBytes: 67_108_864 }, wallClockTimeoutMs: 60_000, maxOutputBytes: 1_048_576, writableProjectPath: "/verification" } }; }
function service(outcome: "reproduced" | "not-reproduced") { return new InvariantReplayService({ database, repositoryRoot: repositories, verificationRoot: workspaces, workspaceBuilder: (compilers) => new VerificationWorkspaceBuilder({ verificationRoot: workspaces, repositoryRoot: repositories, acceptedCompilerVersions: compilers, approvedSourceRoots: ["contracts"], generatorVersion: "0.2.0" }), runner: { run: vi.fn(async (input) => ({ ...worker(outcome), replayPlanHash: input.replayPlanHash, counterexampleHash: input.counterexampleHash, isolation: { ...worker(outcome).isolation!, writableProjectPath: input.workspacePath } })) } }); }

describe("reviewed invariant replay lifecycle", () => {
  it("creates a deterministic artifact without executing and keeps the hypothesis candidate", async () => { const proposalRow = proposal(), run = invariantRun(), value = await service("reproduced").generate(hypothesisId, proposalRow.id, run.id); expect(value.counterexampleHash).toMatch(/^[a-f0-9]{64}$/); expect(listHypothesisInvariantReplayArtifacts(database, hypothesisId)).toHaveLength(1); expect(listHypothesisInvariantReplayRuns(database, hypothesisId)).toHaveLength(0); expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("candidate"); });
  it("preserves a not-reproduced run without evidence or lifecycle change", async () => { const proposalRow = proposal(), run = invariantRun(), replayService = service("not-reproduced"), artifact = await replayService.generate(hypothesisId, proposalRow.id, run.id), replayRun = await replayService.execute(hypothesisId, artifact.id); expect(replayRun.outcome).toBe("not-reproduced"); expect(listInvariantEvidenceReviews(database, hypothesisId)).toEqual([]); expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("candidate"); });
  it("requires explicit relevance review before centralized lifecycle verification", async () => { const proposalRow = proposal(), run = invariantRun(), replayService = service("reproduced"), artifact = await replayService.generate(hypothesisId, proposalRow.id, run.id), replayRun = await replayService.execute(hypothesisId, artifact.id); expect(replayRun.outcome).toBe("reproduced"); expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("candidate"); const review = replayService.review(hypothesisId, proposalRow.id, run.id, replayRun.id); expect(review.provenance).toBe("local-system/manual-review"); expect(review.transitionId).not.toBeNull(); expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("verified"); expect(listHypothesisLifecycleTransitions(database, hypothesisId)).toMatchObject([{ sourceKind: "reviewed-invariant-replay", fromStatus: "candidate", toStatus: "verified" }]); expect(() => replayService.review(hypothesisId, proposalRow.id, run.id, replayRun.id)).toThrow("already reviewed"); });
  it("offers no replay for held-within-bounds results", async () => { const proposalRow = proposal(), run = invariantRun(false); await expect(service("reproduced").generate(hypothesisId, proposalRow.id, run.id)).rejects.toMatchObject({ code: "invalid_state" }); expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("candidate"); });
  it("rebuilds every replay attempt in a fresh run workspace from the immutable artifact", async () => {
    const proposalRow = proposal(), invariant = invariantRun(), replayService = service("reproduced"), artifact = await replayService.generate(hypothesisId, proposalRow.id, invariant.id);
    writeFileSync(path.join(workspaces, artifact.id, "test/ContractHunterReplay.t.sol"), "contract Changed {}");
    const first = await replayService.execute(hypothesisId, artifact.id), second = await replayService.execute(hypothesisId, artifact.id);
    expect(first).toMatchObject({ outcome: "reproduced", artifactId: artifact.id }); expect(second).toMatchObject({ outcome: "reproduced", artifactId: artifact.id }); expect(second.id).not.toBe(first.id);
    expect(readFileSync(path.join(workspaces, first.id, "test/ContractHunterReplay.t.sol"), "utf8")).not.toContain("contract Changed");
    expect(readFileSync(path.join(workspaces, second.id, "test/ContractHunterReplay.t.sol"), "utf8")).toBe(readFileSync(path.join(workspaces, first.id, "test/ContractHunterReplay.t.sol"), "utf8"));
    expect(listHypothesisInvariantReplayRuns(database, hypothesisId)).toHaveLength(2);
  });
  it("records a failed retry when authoritative source no longer regenerates the artifact hashes", async () => {
    const proposalRow = proposal(), invariant = invariantRun(), replayService = service("reproduced"), artifact = await replayService.generate(hypothesisId, proposalRow.id, invariant.id);
    writeFileSync(path.join(repositories, scanId, "contracts/VulnerableAccounting.sol"), `${readFileSync(fixture, "utf8")}\n// changed after artifact creation\n`);
    const retry = await replayService.execute(hypothesisId, artifact.id);
    expect(retry).toMatchObject({ status: "failed", outcome: "failed", errorCode: "replay_manifest_mismatch" });
    expect(getVulnerabilityHypothesis(database, hypothesisId)?.status).toBe("candidate");
  });
});
