import Link from "next/link";
import { findingStatuses, severities, type FindingStatus, type Severity } from "@contracthunter/core";
import { getDatabase, listFindings, listScans } from "@contracthunter/db";
import { FindingStatusBadge, SeverityBadge } from "@/components/badges";

export const dynamic = "force-dynamic";

type Query = { scan?: string; severity?: string; source?: string; status?: string };

export default async function FindingsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const query = await searchParams;
  const database = getDatabase();
  const scanId = query.scan && listScans(database).some((scan) => scan.id === query.scan) ? query.scan : undefined;
  const severity = severities.includes(query.severity as Severity) ? query.severity as Severity : undefined;
  const status = findingStatuses.includes(query.status as FindingStatus) ? query.status as FindingStatus : undefined;
  const source = query.source?.slice(0, 100) || undefined;
  const results = listFindings(database, { scanId, severity, status, source });
  const scans = listScans(database);
  const sources = [...new Set(listFindings(database).map((finding) => finding.source))];
  return <>
    <header className="page-head"><div><div className="eyebrow">Review queue</div><h1>Findings</h1><p className="subhead">Filter and inspect candidate issues from every hunt.</p></div></header>
    <div className="mock-note">V0.1 findings are generated by the mock scanner and must not be treated as real analysis.</div>
    <form className="filter-row">
      <select name="scan" defaultValue={scanId ?? ""} aria-label="Filter by scan"><option value="">All hunts</option>{scans.map((scan) => <option key={scan.id} value={scan.id}>{scan.repositoryName} · {scan.id.slice(0, 8)}</option>)}</select>
      <select name="severity" defaultValue={severity ?? ""} aria-label="Filter by severity"><option value="">All severities</option>{severities.map((item) => <option key={item}>{item}</option>)}</select>
      <select name="source" defaultValue={source ?? ""} aria-label="Filter by source"><option value="">All sources</option>{sources.map((item) => <option key={item}>{item}</option>)}</select>
      <select name="status" defaultValue={status ?? ""} aria-label="Filter by status"><option value="">All statuses</option>{findingStatuses.map((item) => <option key={item}>{item}</option>)}</select>
      <button className="button">FILTER</button>
    </form>
    <div className="table-wrap"><table><thead><tr><th>Severity</th><th>Finding</th><th>Contract</th><th>Source</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{results.map((finding) => <tr key={finding.id}><td><SeverityBadge value={finding.severity} /></td><td className="finding-title"><Link className="repo" href={`/findings/${finding.id}`}>{finding.title}</Link></td><td className="mono">{finding.contract ?? "—"}</td><td>{finding.source}</td><td>{finding.confidence}%</td><td><FindingStatusBadge value={finding.status} /></td></tr>)}{results.length === 0 && <tr><td className="empty" colSpan={6}>No findings match these filters.</td></tr>}</tbody></table></div>
  </>;
}
