import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { counterexampleHash, executableInvariantPlanSchema, invariantPlanHash, invariantReplayPlanHash, invariantReplayPlanSchema } from "@contracthunter/core";
import type { PublicInvariantProposal, PublicInvariantReplayArtifact, PublicInvariantReplayRun, PublicInvariantReview, PublicInvariantRun } from "@/lib/verification/public-invariants";
import { LocalInvariantTesting } from "./local-invariant-testing";

const hypothesisId = crypto.randomUUID(), plan = executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", mode: "fuzz-property", scanId: crypto.randomUUID(), hypothesisId, resolvedCommit: "a".repeat(40), compilerVersion: "0.8.36", primaryContract: "VulnerableAccounting", primarySourcePath: "contracts/VulnerableAccounting.sol", sourceFiles: ["contracts/VulnerableAccounting.sol"], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: "VulnerableAccounting", instanceName: "target" }], property: { name: "accounting", observations: [{ kind: "read-uint", instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }, { kind: "read-balance", target: { kind: "instance", name: "target" }, resultName: "balance" }], assertions: [{ id: "equal", kind: "uint-eq", actual: "recorded", expected: { kind: "result", name: "balance" } }] }, fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }], args: [{ kind: "parameter", name: "amount" }] } });
const proposal: PublicInvariantProposal = { id: crypto.randomUUID(), status: "generated", plan, planHash: "b".repeat(64), hypothesisExpectation: "hypothesis-predicts-property-violation", relationRationale: "The hypothesis predicts divergence.", rationale: "Accounting should match balance.", limitations: [], notPlannableReasons: [], failureCode: null, provider: "mock", model: "model", promptVersion: "invariant-plan-v1", sourceFileCount: 1, totalSourceBytes: 200, contextTruncated: false, inputTokens: 20, outputTokens: 10, totalTokens: 30, estimatedCostUsd: 0.0001, durationMs: 5, createdAt: "2026-08-16T10:00:00.000Z" };
const baseRun: PublicInvariantRun = { id: crypto.randomUUID(), proposalId: proposal.id, status: "completed", outcome: "held-within-bounds", mode: "fuzz-property", planHash: proposal.planHash!, compiler: "0.8.36", configuredRuns: 128, configuredDepth: null, runsExecuted: 128, testCount: 1, passedCount: 1, failedCount: 0, durationMs: 27, dynamicEvidence: [{ planHash: proposal.planHash!, mode: "fuzz-property", propertyName: "accounting", configuredRuns: 128, configuredDepth: null, runsExecuted: 128, propertyOutcome: "held-within-bounds", hypothesisRelation: "neutral", compilerVersion: "0.8.36", isolationProvider: "docker-verification-worker-v1", counterexample: null, summary: "No counterexample found within configured runs." }], failureCode: null, createdAt: "2026-08-16T10:00:00.000Z" };
const render = (proposals: PublicInvariantProposal[], runs: PublicInvariantRun[], replays: PublicInvariantReplayArtifact[] = [], replayRuns: PublicInvariantReplayRun[] = [], reviews: PublicInvariantReview[] = []) => renderToStaticMarkup(<LocalInvariantTesting hypothesisId={hypothesisId} hypothesisStatus="candidate" initialProposals={proposals} initialRuns={runs} initialReplays={replays} initialReplayRuns={replayRuns} initialReviews={reviews} />);
describe("manual invariant workflow UI", () => {
  it("starts with separate proposal and local run controls and no execution", () => { const html = render([], []); expect(html).toContain("Generate invariant proposal"); expect(html).toContain("No local invariant execution"); expect(html).not.toContain("Run invariant locally"); expect(html).not.toContain("Verified"); });
  it("shows reviewed plan, trusted compiler, bounds, and disabled run until validation", () => { const html = render([proposal], []); for (const value of ["Generated preview", "fuzz-property", "VulnerableAccounting", "uint256 amount", "Validate proposal", "Run invariant locally", "128 fuzz runs", "0.8.36", proposal.planHash!]) expect(html).toContain(value); expect(html).toMatch(/<button[^>]+disabled[^>]*>Run invariant locally<\/button>/); });
  it("describes the bounded property outcome without calling it proof or verification", () => { const html = render([proposal], [baseRun]); expect(html).toContain("HELD WITHIN BOUNDS"); expect(html).toContain("bounded property outcome, not formal proof or authoritative hypothesis evidence"); expect(html).toContain("Assertion summary"); expect(html).not.toContain("Mark verified"); });
  it("shows bounded counterexample facts and handler sequence", () => { const failed: PublicInvariantRun = { ...baseRun, mode: "stateful-invariant", outcome: "counterexample-found", failedCount: 1, passedCount: 0, configuredRuns: 64, configuredDepth: 32, dynamicEvidence: [{ ...baseRun.dynamicEvidence[0], mode: "stateful-invariant", propertyOutcome: "counterexample-found", hypothesisRelation: "unreviewed", configuredRuns: 64, configuredDepth: 32, counterexample: { kind: "sequence", parserVersion: "foundry-1.7.1-json-v1", actions: [{ actionName: "takeOwnership", parameterValues: [] }], summary: "Bounded sequence." } }] }; const html = render([proposal], [failed]); expect(html).toContain("COUNTEREXAMPLE FOUND"); expect(html).toContain("takeOwnership()"); expect(html).toContain("unreviewed"); });
  it("renders not-plannable, execution-running, and validation-failure histories distinctly", () => {
    const notPlannable: PublicInvariantProposal = { ...proposal, id: crypto.randomUUID(), status: "not_plannable", plan: null, planHash: null, rationale: "Current semantics cannot express this property.", notPlannableReasons: ["unsupported observation"] };
    expect(render([notPlannable], [])).toContain("Not plannable");
    expect(render([proposal], [{ ...baseRun, status: "running", outcome: null, runsExecuted: null, durationMs: null, dynamicEvidence: [] }])).toContain("RUNNING");
    expect(render([{ ...proposal, status: "failed", plan: null, planHash: null, failureCode: "invalid_invariant_source" }], [])).toContain("invalid_invariant_source");
  });
  it("renders replay available, not reproduced with fresh-workspace retry, reproduced review, and accepted evidence", () => {
    const counterexample = { kind: "single" as const, parserVersion: "foundry-1.7.1-json-v1" as const, parameterValues: [{ name: "amount", type: "uint256" as const, value: "436" }], summary: "Final case." };
    const failed: PublicInvariantRun = { ...baseRun, outcome: "counterexample-found", passedCount: 0, failedCount: 1, runsExecuted: 1, dynamicEvidence: [{ ...baseRun.dynamicEvidence[0], propertyOutcome: "counterexample-found", hypothesisRelation: "unreviewed", runsExecuted: 1, counterexample }] };
    const replayPlan = invariantReplayPlanSchema.parse({ schemaVersion: "contracthunter-invariant-replay-v1", scanId: plan.scanId, hypothesisId, resolvedCommit: plan.resolvedCommit, compilerVersion: plan.compilerVersion, proposalId: proposal.id, invariantRunId: failed.id, invariantPlanHash: invariantPlanHash(plan), propertyName: "accounting", hypothesisExpectation: "hypothesis-predicts-property-violation", counterexample, counterexampleHash: counterexampleHash(counterexample) });
    const replay: PublicInvariantReplayArtifact = { id: crypto.randomUUID(), proposalId: proposal.id, invariantRunId: failed.id, replayPlan, replayPlanHash: invariantReplayPlanHash(replayPlan), counterexampleHash: replayPlan.counterexampleHash, harnessHash: "c".repeat(64), createdAt: baseRun.createdAt };
    expect(render([proposal], [failed], [replay])).toContain("Replay available");
    const notReproduced: PublicInvariantReplayRun = { id: crypto.randomUUID(), artifactId: replay.id, status: "completed", outcome: "not-reproduced", durationMs: 3, failureCode: null, createdAt: baseRun.createdAt };
    const notHtml = render([proposal], [failed], [replay], [notReproduced]); expect(notHtml).toContain("Not reproduced"); expect(notHtml).toContain("Retry replay in fresh workspace");
    const reproduced: PublicInvariantReplayRun = { ...notReproduced, id: crypto.randomUUID(), outcome: "reproduced" };
    expect(render([proposal], [failed], [replay], [reproduced])).toContain("Confirm relevance");
    const review: PublicInvariantReview = { id: crypto.randomUUID(), proposalId: proposal.id, invariantRunId: failed.id, replayRunId: reproduced.id, counterexampleHash: replay.counterexampleHash, action: "confirm-relevance", evidenceId: crypto.randomUUID(), transitionId: crypto.randomUUID(), createdAt: baseRun.createdAt };
    const accepted = render([proposal], [failed], [replay], [reproduced], [review]); expect(accepted).toContain("Evidence accepted"); expect(accepted).toContain("Authoritative supporting dynamic evidence");
  });
});
