import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { executableInvariantPlanSchema } from "@contracthunter/core";
import type { PublicInvariantProposal, PublicInvariantRun } from "@/lib/verification/public-invariants";
import { LocalInvariantTesting } from "./local-invariant-testing";

const hypothesisId = crypto.randomUUID(), plan = executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", mode: "fuzz-property", scanId: crypto.randomUUID(), hypothesisId, resolvedCommit: "a".repeat(40), compilerVersion: "0.8.36", primaryContract: "VulnerableAccounting", primarySourcePath: "contracts/VulnerableAccounting.sol", sourceFiles: ["contracts/VulnerableAccounting.sol"], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: "VulnerableAccounting", instanceName: "target" }], property: { name: "accounting", observations: [{ kind: "read-uint", instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }, { kind: "read-balance", target: { kind: "instance", name: "target" }, resultName: "balance" }], assertions: [{ id: "equal", kind: "uint-eq", actual: "recorded", expected: { kind: "result", name: "balance" } }] }, fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }], args: [{ kind: "parameter", name: "amount" }] } });
const proposal: PublicInvariantProposal = { id: crypto.randomUUID(), status: "generated", plan, planHash: "b".repeat(64), hypothesisExpectation: "hypothesis-predicts-property-violation", relationRationale: "The hypothesis predicts divergence.", rationale: "Accounting should match balance.", limitations: [], notPlannableReasons: [], failureCode: null, provider: "mock", model: "model", promptVersion: "invariant-plan-v1", sourceFileCount: 1, totalSourceBytes: 200, contextTruncated: false, inputTokens: 20, outputTokens: 10, totalTokens: 30, estimatedCostUsd: 0.0001, durationMs: 5, createdAt: "2026-08-16T10:00:00.000Z" };
const baseRun: PublicInvariantRun = { id: crypto.randomUUID(), proposalId: proposal.id, status: "completed", outcome: "held-within-bounds", mode: "fuzz-property", planHash: proposal.planHash!, compiler: "0.8.36", configuredRuns: 128, configuredDepth: null, runsExecuted: 128, testCount: 1, passedCount: 1, failedCount: 0, durationMs: 27, dynamicEvidence: [{ planHash: proposal.planHash!, mode: "fuzz-property", propertyName: "accounting", configuredRuns: 128, configuredDepth: null, runsExecuted: 128, propertyOutcome: "held-within-bounds", hypothesisRelation: "neutral", compilerVersion: "0.8.36", isolationProvider: "docker-verification-worker-v1", counterexample: null, summary: "No counterexample found within configured runs." }], failureCode: null, createdAt: "2026-08-16T10:00:00.000Z" };
const render = (proposals: PublicInvariantProposal[], runs: PublicInvariantRun[]) => renderToStaticMarkup(<LocalInvariantTesting hypothesisId={hypothesisId} hypothesisStatus="candidate" initialProposals={proposals} initialRuns={runs} />);
describe("manual invariant workflow UI", () => {
  it("starts with separate proposal and local run controls and no execution", () => { const html = render([], []); expect(html).toContain("Generate invariant proposal"); expect(html).toContain("No local invariant execution"); expect(html).not.toContain("Run invariant locally"); expect(html).not.toContain("Verified"); });
  it("shows reviewed plan, trusted compiler, bounds, and disabled run until validation", () => { const html = render([proposal], []); for (const value of ["Generated preview", "fuzz-property", "VulnerableAccounting", "uint256 amount", "Validate proposal", "Run invariant locally", "128 fuzz runs", "0.8.36", proposal.planHash!]) expect(html).toContain(value); expect(html).toMatch(/<button[^>]+disabled[^>]*>Run invariant locally<\/button>/); });
  it("describes bounded support without calling it proof or verification", () => { const html = render([proposal], [baseRun]); expect(html).toContain("HELD WITHIN BOUNDS"); expect(html).toContain("supporting dynamic evidence, not formal proof"); expect(html).toContain("Assertion summary"); expect(html).not.toContain("Mark verified"); });
  it("shows bounded counterexample facts and handler sequence", () => { const failed: PublicInvariantRun = { ...baseRun, mode: "stateful-invariant", outcome: "counterexample-found", failedCount: 1, passedCount: 0, configuredRuns: 64, configuredDepth: 32, dynamicEvidence: [{ ...baseRun.dynamicEvidence[0], mode: "stateful-invariant", propertyOutcome: "counterexample-found", hypothesisRelation: "unreviewed", configuredRuns: 64, configuredDepth: 32, counterexample: { kind: "sequence", parserVersion: "foundry-1.7.1-json-v1", actions: [{ actionName: "takeOwnership", parameterValues: [] }], summary: "Bounded sequence." } }] }; const html = render([proposal], [failed]); expect(html).toContain("COUNTEREXAMPLE FOUND"); expect(html).toContain("takeOwnership()"); expect(html).toContain("unreviewed"); });
});
