"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
export type SecurityReviewCostEstimateDTO = { approximateSourceBytes: number; approximateRequestCount: number; selectedReviewers: unknown[]; estimatedCostDisplay: string };
export function SecurityReviewCostEstimate({ estimate }: { estimate: SecurityReviewCostEstimateDTO }) {
  return <div className="hint" style={{ marginTop: 8 }}>Selected reviewers: {estimate.selectedReviewers.length} · Estimated requests: {estimate.approximateRequestCount} · Estimated context: ~{Math.ceil(estimate.approximateSourceBytes / 1024)} KiB · Estimated API cost: ~{estimate.estimatedCostDisplay}. Estimate only — actual cost depends on token usage.</div>;
}
export function SecurityReviewControl({ scanId, enabled, configured, available, stageRunning, label }: { scanId: string; enabled: boolean; configured: boolean; available: boolean; stageRunning: boolean; label: string }) {
  const router = useRouter(); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const [estimate, setEstimate] = useState<SecurityReviewCostEstimateDTO | null>(null);
  useEffect(() => { if (!enabled || !configured || !available) return; void fetch(`/api/scans/${scanId}/security-review`).then((response) => response.ok ? response.json() : null).then(setEstimate).catch(() => undefined); }, [available, configured, enabled, scanId]);
  async function run() { setRunning(true); setError(""); const response = await fetch(`/api/scans/${scanId}/security-review`, { method: "POST" }).catch(() => null); if (!response?.ok) setError(response ? ((await response.json().catch(() => ({}))) as { error?: string }).error ?? "Unable to start security review." : "Unable to start security review."); else { router.refresh(); setTimeout(() => router.refresh(), 1500); } setRunning(false); }
  return <div><button className="button" disabled={running || stageRunning || !enabled || !configured || !available} onClick={() => void run()}>{running ? "STARTING…" : stageRunning ? "SECURITY REVIEW RUNNING…" : label}</button>{estimate && <SecurityReviewCostEstimate estimate={estimate} />}{!available && <div className="hint" style={{ marginTop: 8 }}>Complete AI Protocol Analysis before starting this optional deeper review.</div>}{!enabled && <div className="hint" style={{ marginTop: 8 }}>Set AI_ENABLED=true to enable this stage.</div>}{enabled && !configured && <div className="hint" style={{ marginTop: 8 }}>Configure OPENAI_API_KEY on the server.</div>}{error && <div className="error" style={{ marginTop: 8, marginBottom: 0 }}>{error}</div>}</div>;
}
