import { randomUUID } from "node:crypto";
import { copyFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { executableInvariantPlanSchema, invariantPlanHash, validAIOutput, type ExecutableInvariantEvidence, type ExecutableInvariantPlan, type ProtocolAnalysisResult } from "../packages/core/src";
import { closeDatabase, completeExecutableInvariantRun, createDatabase, createExecutableInvariantProposal, createExecutableInvariantRun, createProtocolAnalysis, createScan, createSecurityReviewerRun, createSecurityReviewPlan, getVulnerabilityHypothesis, insertVulnerabilityHypotheses, listInvariantEvidenceReviews, markExecutableInvariantRunRunning } from "../packages/db/src";
import { ExecutableInvariantService } from "../apps/web/lib/verification/executable-invariant-service";
import { InvariantReplayService } from "../apps/web/lib/verification/invariant-replay-service";
import { ExecutableInvariantWorkerClient, InvariantReplayWorkerClient, VerificationWorkspaceBuilder } from "../packages/scanners/src";

const commit = "c".repeat(40), compilerVersion = "0.8.36", repositoryRoot = "/data/repositories", verificationRoot = "/verification";
const property = { name: "accounting", observations: [{ kind: "read-uint" as const, instanceName: "target", functionName: "totalRecordedBalance", resultName: "recorded" }, { kind: "read-balance" as const, target: { kind: "instance" as const, name: "target" }, resultName: "nativeBalance" }], assertions: [{ id: "conservation", kind: "uint-eq" as const, actual: "recorded", expected: { kind: "result" as const, name: "nativeBalance" } }] };

async function main() {
  if (process.env.CONTRACTHUNTER_PROBE_ISOLATED !== "1") throw new Error("This probe requires explicitly isolated Compose volumes.");
  const database = createDatabase(`/data/replay-probe-${randomUUID()}.db`);
  try {
    const scan = createScan(database, { repositoryUrl: "https://example.invalid/replay-probe", repositoryName: "replay-probe", depth: "quick" }), repository = path.join(repositoryRoot, scan.id);
    await mkdir(path.join(repository, "contracts"), { recursive: true });
    for (const contract of ["VulnerableAccounting", "SafeAccounting", "StatefulAccessControl"]) await copyFile(path.join("/tmp/fixtures/contracts", `${contract}.sol`), path.join(repository, "contracts", `${contract}.sol`));
    database.sqlite.prepare("UPDATE scans SET status='completed', resolved_commit=?, compiler_status='ready', compiler_versions=? WHERE id=?").run(commit, JSON.stringify([compilerVersion]), scan.id);
    const analysis = createProtocolAnalysis(database, { scanId: scan.id, provider: "fixture", requestedModel: "fixture", actualModel: "fixture", promptVersion: "protocol-analysis-v1", result: validAIOutput as unknown as ProtocolAnalysisResult, coverageStatus: "complete", contextManifest: {}, durationMs: 1, inputTokens: 0, outputTokens: 0, totalTokens: 0, requestId: randomUUID() });
    const reviewPlan = createSecurityReviewPlan(database, { scanId: scan.id, protocolAnalysisId: analysis.id, plan: { selected: [], skipped: [], estimatedRequestCount: 0 }, estimatedSourceBytes: 0 });
    const reviewer = createSecurityReviewerRun(database, { planId: reviewPlan.id, scanId: scan.id, protocolAnalysisId: analysis.id, reviewerId: "fixture", reviewerName: "Fixture", selectionReason: "Replay probe", promptVersion: "security-review-fixture-v1", provider: "fixture", requestedModel: "fixture", contextManifest: {} });
    const hypothesis = (title: string) => insertVulnerabilityHypotheses(database, [{ scanId: scan.id, protocolAnalysisId: analysis.id, reviewerId: reviewer.reviewerId, reviewerRunId: reviewer.id, title, category: "state-transition", severity: "low", severityJustification: "Synthetic release probe", confidence: 60, summary: title, rootCause: "Synthetic release probe", preconditions: "[]", attackPath: "[]", impact: "Synthetic release probe", affectedAssets: "[]", affectedContracts: "[]", affectedFunctions: "[]", evidence: "[]", violatedInvariantIds: "[]", relatedInvestigationIds: "[]", falsePositiveRisks: "[]", verificationStrategy: "[]" }])[0];
    const accountingHypothesis = hypothesis("Vulnerable accounting replay"), statefulHypothesis = hypothesis("Stateful access-control replay"), safeHypothesis = hypothesis("Safe accounting negative control"), negativeHypothesis = hypothesis("Deliberately non-reproducing replay");
    const fuzz = (hypothesisId: string, contract: "VulnerableAccounting" | "SafeAccounting") => executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", mode: "fuzz-property", scanId: scan.id, hypothesisId, resolvedCommit: commit, compilerVersion, primaryContract: contract, primarySourcePath: `contracts/${contract}.sol`, sourceFiles: [`contracts/${contract}.sol`], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: contract, instanceName: "target" }], property, fuzzAction: { instanceName: "target", functionName: "record", caller: "attacker", parameters: [{ name: "amount", type: "uint256" }], args: [{ kind: "parameter", name: "amount" }] } });
    const stateful = executableInvariantPlanSchema.parse({ schemaVersion: "contracthunter-invariant-plan-v1", mode: "stateful-invariant", scanId: scan.id, hypothesisId: statefulHypothesis.id, resolvedCommit: commit, compilerVersion, primaryContract: "StatefulAccessControl", primarySourcePath: "contracts/StatefulAccessControl.sol", sourceFiles: ["contracts/StatefulAccessControl.sol"], actors: ["deployer", "attacker"], setup: [{ kind: "deploy", contractName: "StatefulAccessControl", instanceName: "target" }], handlerActions: [{ name: "takeOwnership", instanceName: "target", functionName: "transferOwnership", caller: "attacker", parameters: [], args: [{ kind: "address", source: "actor", name: "attacker" }] }, { name: "touch", instanceName: "target", functionName: "touch", caller: "attacker", parameters: [{ name: "flag", type: "bool" }], args: [{ kind: "parameter", name: "flag" }] }], properties: [{ name: "ownerStable", observations: [{ kind: "read-address", instanceName: "target", functionName: "owner", resultName: "observedOwner" }], assertions: [{ id: "owner", kind: "address-eq", actual: "observedOwner", expected: { kind: "address", source: "actor", name: "deployer" } }] }] });
    const proposal = (hypothesisId: string, plan: ExecutableInvariantPlan) => createExecutableInvariantProposal(database, { hypothesisId, scanId: scan.id, result: { status: "generated", plan, planHash: invariantPlanHash(plan), hypothesisExpectation: "hypothesis-predicts-property-violation", relationRationale: "Synthetic release probe.", rationale: "Synthetic release probe.", limitations: [], notPlannableReasons: [], failureCode: null, provenance: { provider: "mock", requestedModel: "mock", actualModel: "mock", promptVersion: "invariant-plan-v1", generatedAt: new Date().toISOString(), inputTokens: 0, outputTokens: 0, totalTokens: 0, estimatedCostUsd: 0, durationMs: 1, sourceFileCount: 1, totalSourceBytes: 1, sourceContextTruncated: false } }, contextManifest: {}, requestId: null });
    const builder = (compilers: string[]) => new VerificationWorkspaceBuilder({ verificationRoot, repositoryRoot, acceptedCompilerVersions: compilers, approvedSourceRoots: ["contracts"], generatorVersion: "0.2.0" });
    const execution = new ExecutableInvariantService({ database, repositoryRoot, workspaceBuilder: builder, runner: new ExecutableInvariantWorkerClient(verificationRoot) });
    const replay = new InvariantReplayService({ database, repositoryRoot, verificationRoot, workspaceBuilder: builder, runner: new InvariantReplayWorkerClient(verificationRoot) });

    const accountingPlan = fuzz(accountingHypothesis.id, "VulnerableAccounting"), accountingProposal = proposal(accountingHypothesis.id, accountingPlan), accountingRun = await execution.run(accountingHypothesis.id, accountingPlan), accountingArtifact = await replay.generate(accountingHypothesis.id, accountingProposal.id, accountingRun.run.id), accountingReplay = await replay.execute(accountingHypothesis.id, accountingArtifact.id);
    const statefulProposal = proposal(statefulHypothesis.id, stateful), statefulRun = await execution.run(statefulHypothesis.id, stateful), statefulArtifact = await replay.generate(statefulHypothesis.id, statefulProposal.id, statefulRun.run.id), statefulReplay = await replay.execute(statefulHypothesis.id, statefulArtifact.id);
    const safePlan = fuzz(safeHypothesis.id, "SafeAccounting"), safeProposal = proposal(safeHypothesis.id, safePlan), safeRun = await execution.run(safeHypothesis.id, safePlan); let safeReplay = "unexpectedly-available";
    try { await replay.generate(safeHypothesis.id, safeProposal.id, safeRun.run.id); } catch { safeReplay = "unavailable"; }

    const negativePlan = fuzz(negativeHypothesis.id, "VulnerableAccounting"), negativeProposal = proposal(negativeHypothesis.id, negativePlan), negativeRun = createExecutableInvariantRun(database, { plan: negativePlan }); markExecutableInvariantRunRunning(database, negativeRun.id);
    const counterexample = { kind: "single" as const, parserVersion: "foundry-1.7.1-json-v1" as const, parameterValues: [{ name: "amount", type: "uint256" as const, value: "0" }], summary: "Deliberate non-violating replay control." };
    const negativeEvidence: ExecutableInvariantEvidence = { planHash: invariantPlanHash(negativePlan), mode: "fuzz-property", propertyName: "accounting", configuredRuns: 128, configuredDepth: null, runsExecuted: 1, propertyOutcome: "counterexample-found", hypothesisRelation: "unreviewed", compilerVersion, isolationProvider: "release-negative-control", counterexample, summary: "Deliberate replay negative control." };
    completeExecutableInvariantRun(database, negativeRun.id, { evidence: [negativeEvidence], testCount: 1, passedCount: 0, failedCount: 1, runsExecuted: 1, stdoutSummary: "negative control", stderrSummary: "", contentFingerprint: "f".repeat(64), isolationMetadata: "{}", exitCode: 1, durationMs: 1 });
    const negativeArtifact = await replay.generate(negativeHypothesis.id, negativeProposal.id, negativeRun.id), negativeReplay = await replay.execute(negativeHypothesis.id, negativeArtifact.id);
    if (accountingReplay.outcome !== "reproduced" || statefulReplay.outcome !== "reproduced" || negativeReplay.outcome !== "not-reproduced") throw new Error(JSON.stringify({ accountingReplay, statefulReplay, negativeReplay }));
    const lifecycleReview = replay.review(accountingHypothesis.id, accountingProposal.id, accountingRun.run.id, accountingReplay.id);

    process.stdout.write(`${JSON.stringify({ accounting: { run: accountingRun.run.outcome, replay: accountingReplay.outcome, reviewed: lifecycleReview.action, status: getVulnerabilityHypothesis(database, accountingHypothesis.id)?.status }, stateful: { run: statefulRun.run.outcome, replay: statefulReplay.outcome }, safe: { run: safeRun.run.outcome, replay: safeReplay }, nonReproducing: { replay: negativeReplay.outcome, reviews: listInvariantEvidenceReviews(database, negativeHypothesis.id).length, status: getVulnerabilityHypothesis(database, negativeHypothesis.id)?.status }, hashes: { accountingPlan: accountingRun.run.planHash, accountingReplay: accountingArtifact.replayPlanHash, accountingCounterexample: accountingArtifact.counterexampleHash }, freshReplayWorkspace: accountingReplay.id !== accountingArtifact.id })}\n`);
  } finally { closeDatabase(database); }
}
main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`); process.exitCode = 1; });
